ALTER TYPE incident_type ADD VALUE IF NOT EXISTS 'TRAFFIC_JAM';
ALTER TYPE incident_type ADD VALUE IF NOT EXISTS 'VEHICLE_BROKEN';
ALTER TYPE incident_type ADD VALUE IF NOT EXISTS 'PLACE_CLOSED';
ALTER TYPE incident_type ADD VALUE IF NOT EXISTS 'BAD_WEATHER';
ALTER TYPE incident_type ADD VALUE IF NOT EXISTS 'MEMBER_DELAY';
ALTER TYPE incident_type ADD VALUE IF NOT EXISTS 'SLEEP_LATE';
ALTER TYPE incident_type ADD VALUE IF NOT EXISTS 'TOO_TIRED';

ALTER TABLE incidents ADD COLUMN IF NOT EXISTS current_stop_id uuid;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS affected_stop_id uuid;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS estimated_delay_minutes integer;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS needs_ai_reroute boolean NOT NULL DEFAULT false;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS context text;
