ALTER TABLE albums
    ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'NOT_GENERATED',
    ADD COLUMN IF NOT EXISTS summary TEXT,
    ADD COLUMN IF NOT EXISTS mood VARCHAR(32),
    ADD COLUMN IF NOT EXISTS cover_caption TEXT,
    ADD COLUMN IF NOT EXISTS share_caption TEXT,
    ADD COLUMN IF NOT EXISTS hashtags TEXT[] DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS error_message TEXT,
    ADD COLUMN IF NOT EXISTS generated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE album_media
    ADD COLUMN IF NOT EXISTS trip_stop_id UUID REFERENCES trip_stops(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS day_index INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS day_title TEXT,
    ADD COLUMN IF NOT EXISTS day_summary TEXT,
    ADD COLUMN IF NOT EXISTS stop_name TEXT,
    ADD COLUMN IF NOT EXISTS highlight TEXT;

CREATE INDEX IF NOT EXISTS idx_album_media_trip_stop_id ON album_media(trip_stop_id);

ALTER TABLE trip_memories
    ADD COLUMN IF NOT EXISTS album_id UUID REFERENCES albums(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS album_status VARCHAR(32) NOT NULL DEFAULT 'NOT_GENERATED',
    ADD COLUMN IF NOT EXISTS album_error TEXT,
    ADD COLUMN IF NOT EXISTS album_generated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS book_status VARCHAR(32) NOT NULL DEFAULT 'NOT_GENERATED',
    ADD COLUMN IF NOT EXISTS book_url TEXT,
    ADD COLUMN IF NOT EXISTS book_file_path TEXT,
    ADD COLUMN IF NOT EXISTS book_error TEXT,
    ADD COLUMN IF NOT EXISTS book_generated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS reel_status VARCHAR(32) NOT NULL DEFAULT 'NOT_GENERATED',
    ADD COLUMN IF NOT EXISTS reel_storyboard JSONB,
    ADD COLUMN IF NOT EXISTS reel_error TEXT,
    ADD COLUMN IF NOT EXISTS reel_generated_at TIMESTAMPTZ;
