ALTER TABLE trips ADD COLUMN IF NOT EXISTS quality_score INTEGER;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS quality_warning VARCHAR(500);
ALTER TYPE ai_job_kind ADD VALUE IF NOT EXISTS 'TRIP_IMPROVE';
