ALTER TYPE incident_type ADD VALUE IF NOT EXISTS 'TRAFFIC';
ALTER TYPE incident_type ADD VALUE IF NOT EXISTS 'CLOSED_PLACE';
ALTER TYPE incident_type ADD VALUE IF NOT EXISTS 'DELAY';
ALTER TYPE incident_type ADD VALUE IF NOT EXISTS 'LOST';
ALTER TYPE incident_type ADD VALUE IF NOT EXISTS 'VEHICLE_PROBLEM';
ALTER TYPE incident_type ADD VALUE IF NOT EXISTS 'HEALTH';

ALTER TABLE incidents
  ALTER COLUMN status TYPE VARCHAR(30),
  ADD COLUMN IF NOT EXISTS ai_summary TEXT,
  ADD COLUMN IF NOT EXISTS ai_suggestion_json TEXT,
  ADD COLUMN IF NOT EXISTS photo_url TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_incidents_trip_id ON incidents(trip_id);
CREATE INDEX IF NOT EXISTS idx_incidents_trip_status ON incidents(trip_id, status);
