-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "postgis";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- Enumerations
CREATE TYPE app_role        AS ENUM ('ADMIN','MODERATOR','USER');
CREATE TYPE trip_status     AS ENUM ('DRAFT','ACTIVE','COMPLETED','ARCHIVED');
CREATE TYPE member_role     AS ENUM ('OWNER','EDITOR','VIEWER');
CREATE TYPE session_status  AS ENUM ('ACTIVE','ENDED','AUTO_CLOSED');
CREATE TYPE quest_type      AS ENUM ('SOLO','TEAM','COMMUNITY');
CREATE TYPE proof_type      AS ENUM ('PHOTO','GPS','CHECKIN');
CREATE TYPE progress_status AS ENUM ('IN_PROGRESS','COMPLETED','FAILED');
CREATE TYPE sos_status      AS ENUM ('ACTIVE','RESOLVED','FALSE_ALARM');
CREATE TYPE incident_type   AS ENUM ('BREAKDOWN','THEFT','INJURY','WEATHER','OTHER');
CREATE TYPE notif_type      AS ENUM ('TRIP','SOS','QUEST','SOCIAL','PAYMENT','SYSTEM');
CREATE TYPE payment_status  AS ENUM ('PENDING','SUCCEEDED','FAILED','REFUNDED','CANCELLED');
CREATE TYPE sub_status      AS ENUM ('ACTIVE','PAST_DUE','CANCELLED','INCOMPLETE');
CREATE TYPE ai_job_status   AS ENUM ('QUEUED','RUNNING','DONE','FAILED');
CREATE TYPE ai_job_kind     AS ENUM ('TRIP_GENERATE','ALBUM_GENERATE','IMAGE_CLASSIFY','MODERATION');
CREATE TYPE dispatch_channel AS ENUM ('SMS','PUSH','EMAIL','REALTIME');
CREATE TYPE budget_band     AS ENUM ('LOW','MID','HIGH','LUXURY');
CREATE TYPE share_scope     AS ENUM ('VIEW','JOIN');